heat_template_version: 2013-05-23  
description: A simple auto scaling group.  
resources:  
  group:
    type: OS::Heat::AutoScalingGroup
    properties:
#      cooldown: 60
      cooldown: 3
#      desired_capacity: 2
      max_size: 5
      min_size: 1
      resource:
        type: OS::Nova::Server::Cirros

  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group }
#      cooldown: 60
      cooldown: 3
      scaling_adjustment: 1

  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: cpu_util
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 50
      alarm_actions:
        - {get_attr: [scaleup_policy, alarm_url]}
      comparison_operator: gt
      repeat_actions: true

#  cpu_alarm_high:
#    type: OS::Ceilometer::Alarm
#    properties:
#      meter_name: cpu_util
#      statistic: avg
#      period: 60
#      evaluation_periods: 1
#      threshold: 20
#      alarm_actions:
#        - {get_attr: [scaleup_policy, alarm_url]}
#      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}
##      matching_metadata: {'metadata.user_metadata.groupname': {get_resource: group}}
#      comparison_operator: gt
#      repeat_actions: true

outputs:
  scale_up_url:
    description: >
      This URL is the webhook to scale up the group.  You can invoke
      the scale-up operation by doing an HTTP POST to this URL; no
      body nor extra headers are needed.
    value: {get_attr: [scaleup_policy, alarm_url]}
