# https://developer.rackspace.com/blog/openstack-orchestration-in-depth-part-1-introduction-to-heat/
heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: m1.tiny
      key_name: sshkey
      networks:
        - network: demo_net
